const fs = require('fs');
const path = require('path');

// This script ensures a 404.html file exists in the out directory
// This is needed for GitHub Pages to properly handle 404 errors

function generate404() {
  const outDir = path.join(process.cwd(), 'out');
  const notFoundPath = path.join(outDir, '404', 'index.html');
  const rootNotFoundPath = path.join(outDir, '404.html');

  // Make sure the 'out' directory exists
  if (!fs.existsSync(outDir)) {
    console.error('The "out" directory does not exist! Run "next build" first.');
    process.exit(1);
  }

  try {
    // Check if the not-found page was generated by Next.js App Router
    if (fs.existsSync(notFoundPath)) {
      // Copy the not-found page to the root 404.html
      fs.copyFileSync(notFoundPath, rootNotFoundPath);
      console.log('Successfully created 404.html from App Router not-found page');
    } else {
      // If not-found page doesn't exist, use index.html as fallback
      const indexPath = path.join(outDir, 'index.html');
      if (fs.existsSync(indexPath)) {
        fs.copyFileSync(indexPath, rootNotFoundPath);
        console.log('Successfully created 404.html from index.html (fallback)');
      } else {
        console.error('Neither not-found page nor index.html found in "out" directory!');
        process.exit(1);
      }
    }
  } catch (error) {
    console.error('Error creating 404.html:', error);
    process.exit(1);
  }
}

generate404(); 